"""2026 Phish concert seed data sourced from phish.net."""

# Each entry: date (YYYY-MM-DD), venue, city, state_province, state_abbr,
# country, lat, lng, setlist_url (None for future shows)
CONCERTS_2026 = [
    # ── Mexico 4 (Moon Palace, Jan 28-31) ──────────────────────────────────
    {
        "date": "2026-01-28",
        "venue": "Moon Palace",
        "city": "Cancun",
        "state_province": "Quintana Roo",
        "state_abbr": None,
        "country": "Mexico",
        "lat": 21.027,
        "lng": -86.845,
        "setlist_url": "https://phish.net/setlists/phish/2026-01-28.html",
    },
    {
        "date": "2026-01-29",
        "venue": "Moon Palace",
        "city": "Cancun",
        "state_province": "Quintana Roo",
        "state_abbr": None,
        "country": "Mexico",
        "lat": 21.027,
        "lng": -86.845,
        "setlist_url": "https://phish.net/setlists/phish/2026-01-29.html",
    },
    {
        "date": "2026-01-30",
        "venue": "Moon Palace",
        "city": "Cancun",
        "state_province": "Quintana Roo",
        "state_abbr": None,
        "country": "Mexico",
        "lat": 21.027,
        "lng": -86.845,
        "setlist_url": "https://phish.net/setlists/phish/2026-01-30.html",
    },
    {
        "date": "2026-01-31",
        "venue": "Moon Palace",
        "city": "Cancun",
        "state_province": "Quintana Roo",
        "state_abbr": None,
        "country": "Mexico",
        "lat": 21.027,
        "lng": -86.845,
        "setlist_url": "https://phish.net/setlists/phish/2026-01-31.html",
    },
    # ── Sphere Run 1 (Apr 16-18) ───────────────────────────────────────────
    {
        "date": "2026-04-16",
        "venue": "Sphere",
        "city": "Las Vegas",
        "state_province": "Nevada",
        "state_abbr": "NV",
        "country": "USA",
        "lat": 36.121,
        "lng": -115.170,
        "setlist_url": "https://phish.net/setlists/phish/2026-04-16.html",
    },
    {
        "date": "2026-04-17",
        "venue": "Sphere",
        "city": "Las Vegas",
        "state_province": "Nevada",
        "state_abbr": "NV",
        "country": "USA",
        "lat": 36.121,
        "lng": -115.170,
        "setlist_url": "https://phish.net/setlists/phish/2026-04-17.html",
    },
    {
        "date": "2026-04-18",
        "venue": "Sphere",
        "city": "Las Vegas",
        "state_province": "Nevada",
        "state_abbr": "NV",
        "country": "USA",
        "lat": 36.121,
        "lng": -115.170,
        "setlist_url": "https://phish.net/setlists/phish/2026-04-18.html",
    },
    # ── Sphere Run 2 (Apr 23-25) ───────────────────────────────────────────
    {
        "date": "2026-04-23",
        "venue": "Sphere",
        "city": "Las Vegas",
        "state_province": "Nevada",
        "state_abbr": "NV",
        "country": "USA",
        "lat": 36.121,
        "lng": -115.170,
        "setlist_url": "https://phish.net/setlists/phish/2026-04-23.html",
    },
    {
        "date": "2026-04-24",
        "venue": "Sphere",
        "city": "Las Vegas",
        "state_province": "Nevada",
        "state_abbr": "NV",
        "country": "USA",
        "lat": 36.121,
        "lng": -115.170,
        "setlist_url": "https://phish.net/setlists/phish/2026-04-24.html",
    },
    {
        "date": "2026-04-25",
        "venue": "Sphere",
        "city": "Las Vegas",
        "state_province": "Nevada",
        "state_abbr": "NV",
        "country": "USA",
        "lat": 36.121,
        "lng": -115.170,
        "setlist_url": "https://phish.net/setlists/phish/2026-04-25.html",
    },
    # ── Sphere Run 3 (Apr 30 - May 2) ─────────────────────────────────────
    {
        "date": "2026-04-30",
        "venue": "Sphere",
        "city": "Las Vegas",
        "state_province": "Nevada",
        "state_abbr": "NV",
        "country": "USA",
        "lat": 36.121,
        "lng": -115.170,
        "setlist_url": "https://phish.net/setlists/phish/2026-04-30.html",
    },
    {
        "date": "2026-05-01",
        "venue": "Sphere",
        "city": "Las Vegas",
        "state_province": "Nevada",
        "state_abbr": "NV",
        "country": "USA",
        "lat": 36.121,
        "lng": -115.170,
        "setlist_url": "https://phish.net/setlists/phish/2026-05-01.html",
    },
    {
        "date": "2026-05-02",
        "venue": "Sphere",
        "city": "Las Vegas",
        "state_province": "Nevada",
        "state_abbr": "NV",
        "country": "USA",
        "lat": 36.121,
        "lng": -115.170,
        "setlist_url": "https://phish.net/setlists/phish/2026-05-02.html",
    },
    # ── 2026 Summer Tour ───────────────────────────────────────────────────
    {
        "date": "2026-07-07",
        "venue": "Kohl Center",
        "city": "Madison",
        "state_province": "Wisconsin",
        "state_abbr": "WI",
        "country": "USA",
        "lat": 43.073,
        "lng": -89.401,
        "setlist_url": None,
    },
    {
        "date": "2026-07-08",
        "venue": "Kohl Center",
        "city": "Madison",
        "state_province": "Wisconsin",
        "state_abbr": "WI",
        "country": "USA",
        "lat": 43.073,
        "lng": -89.401,
        "setlist_url": None,
    },
    {
        "date": "2026-07-10",
        "venue": "Ruoff Music Center",
        "city": "Noblesville",
        "state_province": "Indiana",
        "state_abbr": "IN",
        "country": "USA",
        "lat": 40.044,
        "lng": -86.027,
        "setlist_url": None,
    },
    {
        "date": "2026-07-11",
        "venue": "Ruoff Music Center",
        "city": "Noblesville",
        "state_province": "Indiana",
        "state_abbr": "IN",
        "country": "USA",
        "lat": 40.044,
        "lng": -86.027,
        "setlist_url": None,
    },
    {
        "date": "2026-07-12",
        "venue": "Ruoff Music Center",
        "city": "Noblesville",
        "state_province": "Indiana",
        "state_abbr": "IN",
        "country": "USA",
        "lat": 40.044,
        "lng": -86.027,
        "setlist_url": None,
    },
    {
        "date": "2026-07-14",
        "venue": "Enmarket Arena",
        "city": "Savannah",
        "state_province": "Georgia",
        "state_abbr": "GA",
        "country": "USA",
        "lat": 32.084,
        "lng": -81.100,
        "setlist_url": None,
    },
    {
        "date": "2026-07-15",
        "venue": "Enmarket Arena",
        "city": "Savannah",
        "state_province": "Georgia",
        "state_abbr": "GA",
        "country": "USA",
        "lat": 32.084,
        "lng": -81.100,
        "setlist_url": None,
    },
    {
        "date": "2026-07-17",
        "venue": "Coastal Credit Union Music Park at Walnut Creek",
        "city": "Raleigh",
        "state_province": "North Carolina",
        "state_abbr": "NC",
        "country": "USA",
        "lat": 35.833,
        "lng": -78.638,
        "setlist_url": None,
    },
    {
        "date": "2026-07-18",
        "venue": "Merriweather Post Pavilion",
        "city": "Columbia",
        "state_province": "Maryland",
        "state_abbr": "MD",
        "country": "USA",
        "lat": 39.212,
        "lng": -76.862,
        "setlist_url": None,
    },
    {
        "date": "2026-07-19",
        "venue": "Merriweather Post Pavilion",
        "city": "Columbia",
        "state_province": "Maryland",
        "state_abbr": "MD",
        "country": "USA",
        "lat": 39.212,
        "lng": -76.862,
        "setlist_url": None,
    },
    {
        "date": "2026-07-21",
        "venue": "Empower Federal Credit Union Amphitheater at Lakeview",
        "city": "Syracuse",
        "state_province": "New York",
        "state_abbr": "NY",
        "country": "USA",
        "lat": 43.048,
        "lng": -76.147,
        "setlist_url": None,
    },
    {
        "date": "2026-07-22",
        "venue": "Madison Square Garden",
        "city": "New York",
        "state_province": "New York",
        "state_abbr": "NY",
        "country": "USA",
        "lat": 40.751,
        "lng": -73.993,
        "setlist_url": None,
    },
    {
        "date": "2026-07-24",
        "venue": "Madison Square Garden",
        "city": "New York",
        "state_province": "New York",
        "state_abbr": "NY",
        "country": "USA",
        "lat": 40.751,
        "lng": -73.993,
        "setlist_url": None,
    },
    {
        "date": "2026-07-25",
        "venue": "Madison Square Garden",
        "city": "New York",
        "state_province": "New York",
        "state_abbr": "NY",
        "country": "USA",
        "lat": 40.751,
        "lng": -73.993,
        "setlist_url": None,
    },
    {
        "date": "2026-07-27",
        "venue": "Madison Square Garden",
        "city": "New York",
        "state_province": "New York",
        "state_abbr": "NY",
        "country": "USA",
        "lat": 40.751,
        "lng": -73.993,
        "setlist_url": None,
    },
    {
        "date": "2026-07-29",
        "venue": "Madison Square Garden",
        "city": "New York",
        "state_province": "New York",
        "state_abbr": "NY",
        "country": "USA",
        "lat": 40.751,
        "lng": -73.993,
        "setlist_url": None,
    },
    {
        "date": "2026-07-31",
        "venue": "Fenway Park",
        "city": "Boston",
        "state_province": "Massachusetts",
        "state_abbr": "MA",
        "country": "USA",
        "lat": 42.347,
        "lng": -71.097,
        "setlist_url": None,
    },
    {
        "date": "2026-08-01",
        "venue": "Fenway Park",
        "city": "Boston",
        "state_province": "Massachusetts",
        "state_abbr": "MA",
        "country": "USA",
        "lat": 42.347,
        "lng": -71.097,
        "setlist_url": None,
    },
    # ── Dick's (Labor Day weekend) ─────────────────────────────────────────
    {
        "date": "2026-09-04",
        "venue": "Dick's Sporting Goods Park",
        "city": "Commerce City",
        "state_province": "Colorado",
        "state_abbr": "CO",
        "country": "USA",
        "lat": 39.806,
        "lng": -104.892,
        "setlist_url": None,
    },
    {
        "date": "2026-09-05",
        "venue": "Dick's Sporting Goods Park",
        "city": "Commerce City",
        "state_province": "Colorado",
        "state_abbr": "CO",
        "country": "USA",
        "lat": 39.806,
        "lng": -104.892,
        "setlist_url": None,
    },
    {
        "date": "2026-09-06",
        "venue": "Dick's Sporting Goods Park",
        "city": "Commerce City",
        "state_province": "Colorado",
        "state_abbr": "CO",
        "country": "USA",
        "lat": 39.806,
        "lng": -104.892,
        "setlist_url": None,
    },
]
