"""Canonical Phish song and album tracklist seed data sourced from phish.net/albums."""

# ---------------------------------------------------------------------------
# All unique songs across every phish.net album.
# Each name is the canonical phish.net spelling.
# ---------------------------------------------------------------------------
SONGS = [
    # ── Junta ──────────────────────────────────────────────────────────────
    {"name": "Fee"},
    {"name": "You Enjoy Myself"},
    {"name": "Esther"},
    {"name": "Golgi Apparatus"},
    {"name": "Foam"},
    {"name": "Dinner and a Movie"},
    {"name": "Divided Sky"},
    {"name": "David Bowie"},
    {"name": "Fluffhead"},
    {"name": "Fluff's Travels"},
    {"name": "Contact"},
    {"name": "Union Federal"},
    {"name": "Sanity"},
    {"name": "Icculus"},
    # ── Lawn Boy ───────────────────────────────────────────────────────────
    {"name": "The Squirming Coil"},
    {"name": "Reba"},
    {"name": "My Sweet One"},
    {"name": "Split Open and Melt"},
    {"name": "The Oh Kee Pa Ceremony"},
    {"name": "Bathtub Gin"},
    {"name": "Run Like an Antelope"},
    {"name": "Lawn Boy"},
    {"name": "Bouncing Around the Room"},
    # ── A Picture of Nectar ────────────────────────────────────────────────
    {"name": "Llama"},
    {"name": "Eliza"},
    {"name": "Cavern"},
    {"name": "Poor Heart"},
    {"name": "Stash"},
    {"name": "Manteca"},
    {"name": "Guelah Papyrus"},
    {"name": "Magilla"},
    {"name": "The Landlady"},
    {"name": "Glide"},
    {"name": "Tweezer"},
    {"name": "The Mango Song"},
    {"name": "Chalk Dust Torture"},
    {"name": "Faht"},
    {"name": "Catapult"},
    {"name": "Tweezer Reprise"},
    # ── Rift ───────────────────────────────────────────────────────────────
    {"name": "Rift"},
    {"name": "Fast Enough for You"},
    {"name": "Lengthwise"},
    {"name": "Maze"},
    {"name": "Sparkle"},
    {"name": "Horn"},
    {"name": "The Wedge"},
    {"name": "My Friend, My Friend"},
    {"name": "Weigh"},
    {"name": "All Things Reconsidered"},
    {"name": "Mound"},
    {"name": "It's Ice"},
    {"name": "The Horse"},
    {"name": "Silent in the Morning"},
    # ── Hoist ──────────────────────────────────────────────────────────────
    {"name": "Julius"},
    {"name": "Down with Disease"},
    {"name": "If I Could"},
    {"name": "Riker's Mailbox"},
    {"name": "Axilla (Part II)"},
    {"name": "Lifeboy"},
    {"name": "Sample in a Jar"},
    {"name": "Wolfman's Brother"},
    {"name": "Scent of a Mule"},
    {"name": "Dog Faced Boy"},
    {"name": "Demand"},
    # ── Billy Breathes ─────────────────────────────────────────────────────
    {"name": "Free"},
    {"name": "Character Zero"},
    {"name": "Waste"},
    {"name": "Taste"},
    {"name": "Cars Trucks Buses"},
    {"name": "Talk"},
    {"name": "Theme from the Bottom"},
    {"name": "Train Song"},
    {"name": "Bliss"},
    {"name": "Billy Breathes"},
    {"name": "Swept Away"},
    {"name": "Steep"},
    {"name": "Prince Caspian"},
    # ── The Story of the Ghost ─────────────────────────────────────────────
    {"name": "Ghost"},
    {"name": "Birds of a Feather"},
    {"name": "Meat"},
    {"name": "Guyute"},
    {"name": "Fikus"},
    {"name": "Shafty"},
    {"name": "Limb By Limb"},
    {"name": "Frankie Says"},
    {"name": "Brian and Robert"},
    {"name": "Water in the Sky"},
    {"name": "Roggae"},
    {"name": "Wading in the Velvet Sea"},
    {"name": "The Moma Dance"},
    {"name": "End of Session"},
    # ── Farmhouse ──────────────────────────────────────────────────────────
    {"name": "Farmhouse"},
    {"name": "Twist"},
    {"name": "Bug"},
    {"name": "Back on the Train"},
    {"name": "Heavy Things"},
    {"name": "Gotta Jibboo"},
    {"name": "Dirt"},
    {"name": "Piper"},
    {"name": "Sleep"},
    {"name": "The Inlaw Josie Wales"},
    {"name": "Sand"},
    {"name": "First Tube"},
    {"name": "Driver"},
    {"name": "Mountains in the Mist"},
    # ── Round Room ─────────────────────────────────────────────────────────
    {"name": "Pebbles and Marbles"},
    {"name": "Anything But Me"},
    {"name": "Round Room"},
    {"name": "Mexican Cousin"},
    {"name": "Friday"},
    {"name": "Seven Below"},
    {"name": "Mock Song"},
    {"name": "46 Days"},
    {"name": "All of These Dreams"},
    {"name": "Walls of the Cave"},
    {"name": "Thunderhead"},
    {"name": "Waves"},
    # ── Undermind ──────────────────────────────────────────────────────────
    {"name": "Scents and Subtle Sounds (Intro)"},
    {"name": "Undermind"},
    {"name": "The Connection"},
    {"name": "A Song I Heard the Ocean Sing"},
    {"name": "Army of One"},
    {"name": "Crowd Control"},
    {"name": "Maggie's Revenge"},
    {"name": "Nothing"},
    {"name": "Two Versions of Me"},
    {"name": "Access Me"},
    {"name": "Scents and Subtle Sounds"},
    {"name": "Tomorrow's Song"},
    {"name": "Secret Smile"},
    {"name": "Grind"},
    {"name": "Tiny"},
    # ── Joy ────────────────────────────────────────────────────────────────
    {"name": "Backwards Down the Number Line"},
    {"name": "Stealing Time From the Faulty Plan"},
    {"name": "Joy"},
    {"name": "Sugar Shack"},
    {"name": "Ocelot"},
    {"name": "Kill Devil Falls"},
    {"name": "Light"},
    {"name": "I Been Around"},
    {"name": "Time Turns Elastic"},
    {"name": "Twenty Years Later"},
    # ── Fuego ──────────────────────────────────────────────────────────────
    {"name": "Fuego"},
    {"name": "The Line"},
    {"name": "Devotion to a Dream"},
    {"name": "Halfway to the Moon"},
    {"name": "Winterqueen"},
    {"name": "Sing Monica"},
    {"name": "555"},
    {"name": "Waiting All Night"},
    {"name": "Wombat"},
    {"name": "Wingsuit"},
    # ── Big Boat ───────────────────────────────────────────────────────────
    {"name": "Friends"},
    {"name": "Breath and Burning"},
    {"name": "Home"},
    {"name": "Blaze On"},
    {"name": "Tide Turns"},
    {"name": "Things People Do"},
    {"name": "Waking Up Dead"},
    {"name": "Running Out of Time"},
    {"name": "No Men In No Man's Land"},
    {"name": "Miss You"},
    {"name": "I Always Wanted It This Way"},
    {"name": "More"},
    {"name": "Petrichor"},
    # ── Sigma Oasis ────────────────────────────────────────────────────────
    {"name": "Sigma Oasis"},
    {"name": "Leaves"},
    {"name": "Everything's Right"},
    {"name": "Mercury"},
    {"name": "Shade"},
    {"name": "Evening Song"},
    {"name": "Steam"},
    {"name": "A Life Beyond The Dream"},
    {"name": "Thread"},
    # ── Evolve ─────────────────────────────────────────────────────────────
    {"name": "Hey Stranger"},
    {"name": "Oblivion"},
    {"name": "Evolve"},
    {"name": "A Wave of Hope"},
    {"name": "Pillow Jets"},
    {"name": "Lonely Trip"},
    {"name": "Life Saving Gun"},
    {"name": "Monsters"},
    {"name": "Ether Edge"},
    {"name": "Human Nature"},
    {"name": "Valdese"},
    {"name": "The Well"},
    {"name": "Mercy"},
    # ── The White Tape ─────────────────────────────────────────────────────
    {"name": "Alumni Blues"},
    {"name": "And So to Bed"},
    {"name": "AC/DC Bag"},
    {"name": "Fuck Your Face"},
    {"name": "Slave to the Traffic Light"},
    {"name": "Aftermath"},
    {"name": "Ingest"},
    {"name": "NO2"},
    {"name": "Dog Log"},
    {"name": "He Ent to the Bog"},
    {"name": "Minkin"},
    {"name": "Letter to Jimmy Page"},
    # ── The Siket Disc ─────────────────────────────────────────────────────
    {"name": "My Left Toe"},
    {"name": "The Name is Slick"},
    {"name": "What's the Use?"},
    {"name": "Fish Bass"},
    {"name": "Quadrophonic Toppling"},
    {"name": "The Happy Whip and Dung Song"},
    {"name": "Insects"},
    {"name": "Title Track"},
    {"name": "Albert"},
    # ── Party Time ─────────────────────────────────────────────────────────
    {"name": "Party Time"},
    {"name": "Alaska"},
    {"name": "Windy City"},
    {"name": "In a Misty Glade"},
    {"name": "Gone"},
    {"name": "Only a Dream"},
    {"name": "The Birdwatcher"},
    {"name": "Let Me Lie"},
    {"name": "If I Told You"},
    {"name": "Splinters of Hail"},
    {"name": "Can't Come Back"},
    {"name": "Shrine"},
    {"name": "Liquid Time"},
    # ── A Live One (new songs) ─────────────────────────────────────────────
    {"name": "Gumbo"},
    {"name": "Montana"},
    {"name": "Wilson"},
    {"name": "Simple"},
    {"name": "Harry Hood"},
    # ── Hampton Comes Alive (new songs) ────────────────────────────────────
    {"name": "Rock and Roll Part Two"},
    {"name": "Tube"},
    {"name": "Quinn the Eskimo (The Mighty Quinn)"},
    {"name": "Funky Bitch"},
    {"name": "Possum"},
    {"name": "Axilla"},
    {"name": "Roses Are Free"},
    {"name": "Gettin' Jiggy Wit' It"},
    {"name": "Big Black Furry Creature from Mars"},
    {"name": "Cry Baby Cry"},
    {"name": "Boogie On Reggae Woman"},
    {"name": "NICU"},
    {"name": "Dogs Stole Things"},
    {"name": "Nellie Kane"},
    {"name": "Bold As Love"},
    {"name": "Sabotage"},
    {"name": "Mike's Song"},
    {"name": "Ha Ha Ha"},
    {"name": "Weekapaug Groove"},
    {"name": "Tubthumping"},
    # ── Live Phish 01 (new songs) ──────────────────────────────────────────
    {"name": "Suzy Greenberg"},
    {"name": "Makisupa Policeman"},
    {"name": "Tela"},
    {"name": "Frankenstein"},
    {"name": "The Curtain"},
    {"name": "Timber (Jerry the Mule)"},
    {"name": "Keyboard Army"},
    {"name": "Halley's Comet"},
    # ── Live Phish 02 (new songs) ──────────────────────────────────────────
    {"name": "The Lizards"},
    {"name": "Also Sprach Zarathustra"},
    {"name": "Harpua"},
    # ── Live Phish 03 (new songs) ──────────────────────────────────────────
    {"name": "Punch You in the Eye"},
    {"name": "Albuquerque"},
    {"name": "Carini"},
    {"name": "Drowned"},
    {"name": "Crosseyed and Painless"},
    {"name": "Loving Cup"},
    # ── Live Phish 04 (new songs) ──────────────────────────────────────────
    {"name": "Cities"},
    {"name": "Walk Away"},
    # ── Live Phish 05 (new songs) ──────────────────────────────────────────
    {"name": "My Soul"},
    {"name": "Rock and Roll"},
    # ── Live Phish 06 (new songs) ──────────────────────────────────────────
    {"name": "Ya Mar"},
    {"name": "Runaway Jim"},
    {"name": "The Old Home Place"},
    {"name": "Vultures"},
    {"name": "When the Circus Comes"},
    {"name": "Buried Alive"},
    {"name": "Mirror in the Bathroom"},
    {"name": "Buffalo Bill"},
    {"name": "I Am Hydrogen"},
    {"name": "Wipe Out"},
    # ── Live Phish 08 (new songs) ──────────────────────────────────────────
    {"name": "Back at the Chicken Shack"},
    {"name": "While My Guitar Gently Weeps"},
    # ── Live Phish 09 (new songs) ──────────────────────────────────────────
    {"name": "Colonel Forbin's Ascent"},
    {"name": "Fly Famous Mockingbird"},
    {"name": "The Fishin' Hole"},
    {"name": "Donna Lee"},
    {"name": "The Man Who Stepped Into Yesterday"},
    {"name": "Avenu Malkenu"},
    {"name": "La Grange"},
    # ── Live Phish 10 (new songs) ──────────────────────────────────────────
    {"name": "Big Ball Jam"},
    {"name": "Jesus Just Left Chicago"},
    {"name": "Carolina"},
    # ── Live Phish 13 (new songs — Halloween '94: Beatles White Album) ─────
    {"name": "Sleeping Monkey"},
    {"name": "Amazing Grace"},
    {"name": "Costume Contest"},
    {"name": "Back in the U.S.S.R."},
    {"name": "Dear Prudence"},
    {"name": "Glass Onion"},
    {"name": "Ob-La-Di, Ob-La-Da"},
    {"name": "Wild Honey Pie"},
    {"name": "The Continuing Story of Bungalow Bill"},
    {"name": "Happiness Is a Warm Gun"},
    {"name": "Martha My Dear"},
    {"name": "I'm So Tired"},
    {"name": "Blackbird"},
    {"name": "Piggies"},
    {"name": "Rocky Raccoon"},
    {"name": "Don't Pass Me By"},
    {"name": "Why Don't We Do It in the Road?"},
    {"name": "I Will"},
    {"name": "Julia"},
    {"name": "Birthday"},
    {"name": "Yer Blues"},
    {"name": "Mother Nature's Son"},
    {"name": "Everybody's Got Something to Hide Except Me and My Monkey"},
    {"name": "Sexy Sadie"},
    {"name": "Helter Skelter"},
    {"name": "Long Long Long"},
    {"name": "Revolution 1"},
    {"name": "Honey Pie"},
    {"name": "Savoy Truffle"},
    {"name": "Revolution 9"},
    # ── Live Phish 14 (new songs — Halloween '95: The Who Quadrophenia) ────
    {"name": "I Am the Sea"},
    {"name": "The Real Me"},
    {"name": "Quadrophenia"},
    {"name": "Cut My Hair"},
    {"name": "The Punk Meets the Godfather"},
    {"name": "I'm One"},
    {"name": "The Dirty Jobs"},
    {"name": "Helpless Dancer"},
    {"name": "Is It In My Head?"},
    {"name": "I've Had Enough"},
    {"name": "5:15"},
    {"name": "Sea and Sand"},
    {"name": "Bell Boy"},
    {"name": "Doctor Jimmy"},
    {"name": "The Rock"},
    {"name": "Love, Reign O'er Me"},
    {"name": "A Day in the Life"},
    {"name": "My Generation"},
    # ── Live Phish 15 (new songs — Halloween '96: Talking Heads) ──────────
    {"name": "Highway to Hell"},
    {"name": "The Star-Spangled Banner"},
    {"name": "Born Under Punches (The Heat Goes On)"},
    {"name": "The Great Curve"},
    {"name": "Once in a Lifetime"},
    {"name": "Houses in Motion"},
    {"name": "Seen and Not Seen"},
    {"name": "Listening Wind"},
    {"name": "The Overload"},
    {"name": "Brother"},
    # ── Live Phish 16 (new songs — Halloween '98: Velvet Underground) ──────
    {"name": "Sneakin' Sally Thru the Alley"},
    {"name": "Who Loves the Sun?"},
    {"name": "Sweet Jane"},
    {"name": "Cool It Down"},
    {"name": "New Age"},
    {"name": "Head Held High"},
    {"name": "Lonesome Cowboy Bill"},
    {"name": "I Found a Reason"},
    {"name": "Train Round the Bend"},
    {"name": "Oh! Sweet Nuthin'"},
    {"name": "Free Bird"},
    # ── Live Phish 17 (new songs) ──────────────────────────────────────────
    {"name": "Beauty of My Dreams"},
    {"name": "California Love"},
    # ── Live Phish 18 (new songs) ──────────────────────────────────────────
    {"name": "Sparks"},
    {"name": "Cannonball"},
    {"name": "Purple Rain"},
    {"name": "Yerushalayim Shel Zahav"},
    # ── Live Phish 19 (new songs) ──────────────────────────────────────────
    {"name": "Flat Fee"},
    {"name": "Rocky Top"},
    {"name": "Moose the Mooche"},
    {"name": "Touch Me"},
    {"name": "Sweet Adeline"},
    # ── Live Phish 20 (new songs) ──────────────────────────────────────────
    {"name": "Uncle Pen"},
    {"name": "I Didn't Know"},
    {"name": "Cracklin' Rosie"},
    {"name": "Good Times Bad Times"},
    {"name": "My Long Journey Home"},
]

# ---------------------------------------------------------------------------
# Per-album tracklists (in track order, deduplicated within each album).
# Song names must exactly match SONGS entries above.
# ---------------------------------------------------------------------------
ALBUM_SONGS: dict[str, list[str]] = {
    "The White Tape": [
        "Alumni Blues",
        "And So to Bed",
        "You Enjoy Myself",
        "AC/DC Bag",
        "Fuck Your Face",
        "Divided Sky",
        "Slave to the Traffic Light",
        "Aftermath",
        "Ingest",
        "NO2",
        "Fluff's Travels",
        "Dog Log",
        "He Ent to the Bog",
        "Run Like an Antelope",
        "Minkin",
        "Letter to Jimmy Page",
    ],
    "Junta": [
        "Fee",
        "You Enjoy Myself",
        "Esther",
        "Golgi Apparatus",
        "Foam",
        "Dinner and a Movie",
        "Divided Sky",
        "David Bowie",
        "Fluffhead",
        "Fluff's Travels",
        "Contact",
        "Union Federal",
        "Sanity",
        "Icculus",
    ],
    "Lawn Boy": [
        "The Squirming Coil",
        "Reba",
        "My Sweet One",
        "Split Open and Melt",
        "The Oh Kee Pa Ceremony",
        "Bathtub Gin",
        "Run Like an Antelope",
        "Lawn Boy",
        "Bouncing Around the Room",
    ],
    "A Picture of Nectar": [
        "Llama",
        "Eliza",
        "Cavern",
        "Poor Heart",
        "Stash",
        "Manteca",
        "Guelah Papyrus",
        "Magilla",
        "The Landlady",
        "Glide",
        "Tweezer",
        "The Mango Song",
        "Chalk Dust Torture",
        "Faht",
        "Catapult",
        "Tweezer Reprise",
    ],
    "Rift": [
        "Rift",
        "Fast Enough for You",
        "Lengthwise",
        "Maze",
        "Sparkle",
        "Horn",
        "The Wedge",
        "My Friend, My Friend",
        "Weigh",
        "All Things Reconsidered",
        "Mound",
        "It's Ice",
        "The Horse",
        "Silent in the Morning",
    ],
    "Hoist": [
        "Julius",
        "Down with Disease",
        "If I Could",
        "Riker's Mailbox",
        "Axilla (Part II)",
        "Lifeboy",
        "Sample in a Jar",
        "Wolfman's Brother",
        "Scent of a Mule",
        "Dog Faced Boy",
        "Demand",
    ],
    "Billy Breathes": [
        "Free",
        "Character Zero",
        "Waste",
        "Taste",
        "Cars Trucks Buses",
        "Talk",
        "Theme from the Bottom",
        "Train Song",
        "Bliss",
        "Billy Breathes",
        "Swept Away",
        "Steep",
        "Prince Caspian",
    ],
    "The Story of the Ghost": [
        "Ghost",
        "Birds of a Feather",
        "Meat",
        "Guyute",
        "Fikus",
        "Shafty",
        "Limb By Limb",
        "Frankie Says",
        "Brian and Robert",
        "Water in the Sky",
        "Roggae",
        "Wading in the Velvet Sea",
        "The Moma Dance",
        "End of Session",
    ],
    "Farmhouse": [
        "Farmhouse",
        "Twist",
        "Bug",
        "Back on the Train",
        "Heavy Things",
        "Gotta Jibboo",
        "Dirt",
        "Piper",
        "Sleep",
        "The Inlaw Josie Wales",
        "Sand",
        "First Tube",
        "Driver",
        "Mountains in the Mist",
    ],
    "Round Room": [
        "Pebbles and Marbles",
        "Anything But Me",
        "Round Room",
        "Mexican Cousin",
        "Friday",
        "Seven Below",
        "Mock Song",
        "46 Days",
        "All of These Dreams",
        "Walls of the Cave",
        "Thunderhead",
        "Waves",
    ],
    "Undermind": [
        "Scents and Subtle Sounds (Intro)",
        "Undermind",
        "The Connection",
        "A Song I Heard the Ocean Sing",
        "Army of One",
        "Crowd Control",
        "Maggie's Revenge",
        "Nothing",
        "Two Versions of Me",
        "Access Me",
        "Scents and Subtle Sounds",
        "Tomorrow's Song",
        "Secret Smile",
        "Grind",
        "Tiny",
    ],
    "Joy": [
        "Backwards Down the Number Line",
        "Stealing Time From the Faulty Plan",
        "Joy",
        "Sugar Shack",
        "Ocelot",
        "Kill Devil Falls",
        "Light",
        "I Been Around",
        "Time Turns Elastic",
        "Twenty Years Later",
    ],
    "Fuego": [
        "Fuego",
        "The Line",
        "Devotion to a Dream",
        "Halfway to the Moon",
        "Winterqueen",
        "Sing Monica",
        "555",
        "Waiting All Night",
        "Wombat",
        "Wingsuit",
    ],
    "Big Boat": [
        "Friends",
        "Breath and Burning",
        "Home",
        "Blaze On",
        "Tide Turns",
        "Things People Do",
        "Waking Up Dead",
        "Running Out of Time",
        "No Men In No Man's Land",
        "Miss You",
        "I Always Wanted It This Way",
        "More",
        "Petrichor",
    ],
    "Sigma Oasis": [
        "Sigma Oasis",
        "Leaves",
        "Everything's Right",
        "Mercury",
        "Shade",
        "Evening Song",
        "Steam",
        "A Life Beyond The Dream",
        "Thread",
    ],
    "Evolve": [
        "Hey Stranger",
        "Oblivion",
        "Evolve",
        "A Wave of Hope",
        "Pillow Jets",
        "Lonely Trip",
        "Life Saving Gun",
        "Monsters",
        "Ether Edge",
        "Human Nature",
        "Valdese",
        "The Well",
        "Mercy",
    ],
    "The Siket Disc": [
        "My Left Toe",
        "The Name is Slick",
        "What's the Use?",
        "Fish Bass",
        "Quadrophonic Toppling",
        "The Happy Whip and Dung Song",
        "Insects",
        "Title Track",
        "Albert",
    ],
    "Party Time": [
        "Party Time",
        "Alaska",
        "Windy City",
        "In a Misty Glade",
        "Gone",
        "Only a Dream",
        "The Birdwatcher",
        "Let Me Lie",
        "If I Told You",
        "Splinters of Hail",
        "Can't Come Back",
        "Shrine",
        "Liquid Time",
    ],
    "A Live One": [
        "Bouncing Around the Room",
        "Stash",
        "Gumbo",
        "Montana",
        "You Enjoy Myself",
        "Chalk Dust Torture",
        "Slave to the Traffic Light",
        "Wilson",
        "Tweezer",
        "Simple",
        "Harry Hood",
        "The Squirming Coil",
    ],
    "Hampton Comes Alive": [
        "Rock and Roll Part Two",
        "Tube",
        "Quinn the Eskimo (The Mighty Quinn)",
        "Funky Bitch",
        "Guelah Papyrus",
        "Rift",
        "Meat",
        "Stash",
        "Train Song",
        "Possum",
        "Roggae",
        "Driver",
        "Split Open and Melt",
        "Bathtub Gin",
        "Piper",
        "Axilla",
        "Roses Are Free",
        "Farmhouse",
        "Gettin' Jiggy Wit' It",
        "Harry Hood",
        "Character Zero",
        "Cavern",
        "Wilson",
        "Big Black Furry Creature from Mars",
        "Lawn Boy",
        "Divided Sky",
        "Cry Baby Cry",
        "Boogie On Reggae Woman",
        "NICU",
        "Dogs Stole Things",
        "Nellie Kane",
        "Foam",
        "Wading in the Velvet Sea",
        "Guyute",
        "Bold As Love",
        "Sabotage",
        "Mike's Song",
        "Simple",
        "The Wedge",
        "The Mango Song",
        "Free",
        "Ha Ha Ha",
        "Weekapaug Groove",
        "Tubthumping",
    ],
    "Live Phish 01": [
        "Suzy Greenberg",
        "Llama",
        "Horn",
        "Foam",
        "Makisupa Policeman",
        "Split Open and Melt",
        "Tela",
        "Taste",
        "My Sweet One",
        "Frankenstein",
        "The Curtain",
        "Tweezer",
        "Timber (Jerry the Mule)",
        "Keyboard Army",
        "Halley's Comet",
        "NICU",
        "Slave to the Traffic Light",
        "Bold As Love",
    ],
    "Live Phish 02": [
        "Golgi Apparatus",
        "Down with Disease",
        "NO2",
        "Stash",
        "The Lizards",
        "Cavern",
        "The Horse",
        "Silent in the Morning",
        "Maze",
        "Sparkle",
        "Sample in a Jar",
        "Run Like an Antelope",
        "Catapult",
        "Harpua",
        "Also Sprach Zarathustra",
        "AC/DC Bag",
        "Scent of a Mule",
        "Harry Hood",
        "Contact",
        "Chalk Dust Torture",
        "Suzy Greenberg",
    ],
    "Live Phish 03": [
        "Punch You in the Eye",
        "Reba",
        "Albuquerque",
        "Carini",
        "The Oh Kee Pa Ceremony",
        "Suzy Greenberg",
        "Drowned",
        "Crosseyed and Painless",
        "Dog Faced Boy",
        "Prince Caspian",
        "Loving Cup",
        "Driver",
        "The Inlaw Josie Wales",
        "Sample in a Jar",
    ],
    "Live Phish 04": [
        "Carini",
        "The Curtain",
        "Cities",
        "Gumbo",
        "Llama",
        "Fee",
        "Heavy Things",
        "Split Open and Melt",
        "Back on the Train",
        "Twist",
        "Walk Away",
        "Also Sprach Zarathustra",
        "Sleep",
        "The Squirming Coil",
    ],
    "Live Phish 05": [
        "Punch You in the Eye",
        "NICU",
        "My Soul",
        "Poor Heart",
        "Wolfman's Brother",
        "First Tube",
        "Llama",
        "Guyute",
        "Run Like an Antelope",
        "Heavy Things",
        "Piper",
        "Rock and Roll",
        "Tweezer",
        "Walk Away",
        "Twist",
        "The Horse",
        "Silent in the Morning",
        "Possum",
        "Suzy Greenberg",
        "Tweezer Reprise",
    ],
    "Live Phish 06": [
        "Funky Bitch",
        "Ya Mar",
        "Carini",
        "Runaway Jim",
        "Meat",
        "Reba",
        "The Old Home Place",
        "Dogs Stole Things",
        "Vultures",
        "When the Circus Comes",
        "Birds of a Feather",
        "Buried Alive",
        "Wipe Out",
        "Chalk Dust Torture",
        "Mirror in the Bathroom",
        "Dog Log",
        "Sanity",
        "Buffalo Bill",
        "Mike's Song",
        "I Am Hydrogen",
        "Weekapaug Groove",
        "Run Like an Antelope",
        "Wading in the Velvet Sea",
        "Golgi Apparatus",
    ],
    "Live Phish 08": [
        "Wilson",
        "Chalk Dust Torture",
        "Roggae",
        "Water in the Sky",
        "Back at the Chicken Shack",
        "Sparkle",
        "Bathtub Gin",
        "Golgi Apparatus",
        "Tweezer",
        "Mountains in the Mist",
        "Birds of a Feather",
        "When the Circus Comes",
        "Fluffhead",
        "While My Guitar Gently Weeps",
        "Tweezer Reprise",
    ],
    "Live Phish 09": [
        "Fluffhead",
        "Colonel Forbin's Ascent",
        "Fly Famous Mockingbird",
        "Harry Hood",
        "Split Open and Melt",
        "Divided Sky",
        "You Enjoy Myself",
        "Possum",
        "The Fishin' Hole",
        "Bold As Love",
        "Ya Mar",
        "Slave to the Traffic Light",
        "AC/DC Bag",
        "Donna Lee",
        "Funky Bitch",
        "Foam",
        "David Bowie",
        "The Man Who Stepped Into Yesterday",
        "Avenu Malkenu",
        "Suzy Greenberg",
        "Dinner and a Movie",
        "Run Like an Antelope",
        "Contact",
        "The Lizards",
        "La Grange",
    ],
    "Live Phish 10": [
        "Llama",
        "Guelah Papyrus",
        "Rift",
        "Gumbo",
        "Maze",
        "If I Could",
        "Scent of a Mule",
        "Stash",
        "Golgi Apparatus",
        "Also Sprach Zarathustra",
        "Mike's Song",
        "Simple",
        "Catapult",
        "Icculus",
        "The Man Who Stepped Into Yesterday",
        "Avenu Malkenu",
        "Fluffhead",
        "My Sweet One",
        "Big Ball Jam",
        "Jesus Just Left Chicago",
        "Sample in a Jar",
        "Carolina",
        "Cavern",
        "Demand",
        "Run Like an Antelope",
    ],
    "Live Phish 13": [
        # Set 1 + Set 3
        "Frankenstein",
        "Sparkle",
        "Simple",
        "Divided Sky",
        "Harpua",
        "Julius",
        "The Horse",
        "Silent in the Morning",
        "Reba",
        "Golgi Apparatus",
        # Set 2: Beatles White Album (Halloween '94)
        "Back in the U.S.S.R.",
        "Dear Prudence",
        "Glass Onion",
        "Ob-La-Di, Ob-La-Da",
        "Wild Honey Pie",
        "The Continuing Story of Bungalow Bill",
        "While My Guitar Gently Weeps",
        "Happiness Is a Warm Gun",
        "Martha My Dear",
        "I'm So Tired",
        "Blackbird",
        "Piggies",
        "Rocky Raccoon",
        "Don't Pass Me By",
        "Why Don't We Do It in the Road?",
        "I Will",
        "Julia",
        "Birthday",
        "Yer Blues",
        "Mother Nature's Son",
        "Everybody's Got Something to Hide Except Me and My Monkey",
        "Sexy Sadie",
        "Helter Skelter",
        "Long Long Long",
        "Revolution 1",
        "Honey Pie",
        "Savoy Truffle",
        "Cry Baby Cry",
        "Revolution 9",
        # Set 3
        "David Bowie",
        "Bouncing Around the Room",
        "Slave to the Traffic Light",
        "Rift",
        "Sleeping Monkey",
        "Poor Heart",
        "Run Like an Antelope",
        "Amazing Grace",
        "Costume Contest",
        "The Squirming Coil",
    ],
    "Live Phish 14": [
        # Set 1
        "Icculus",
        "Divided Sky",
        "Wilson",
        "Ya Mar",
        "Sparkle",
        "Free",
        "Guyute",
        "Run Like an Antelope",
        "Harpua",
        # Set 2: The Who's Quadrophenia (Halloween '95)
        "I Am the Sea",
        "The Real Me",
        "Quadrophenia",
        "Cut My Hair",
        "The Punk Meets the Godfather",
        "I'm One",
        "The Dirty Jobs",
        "Helpless Dancer",
        "Is It In My Head?",
        "I've Had Enough",
        "5:15",
        "Sea and Sand",
        "Drowned",
        "Bell Boy",
        "Doctor Jimmy",
        "The Rock",
        "Love, Reign O'er Me",
        # Set 3
        "You Enjoy Myself",
        "Jesus Just Left Chicago",
        "A Day in the Life",
        "Suzy Greenberg",
        "My Generation",
    ],
    "Live Phish 15": [
        # Set 1
        "Sanity",
        "Highway to Hell",
        "Down with Disease",
        "You Enjoy Myself",
        "Prince Caspian",
        "Reba",
        "Colonel Forbin's Ascent",
        "Fly Famous Mockingbird",
        "Character Zero",
        # Set 2: Talking Heads' Remain in Light (Halloween '96)
        "The Star-Spangled Banner",
        "Born Under Punches (The Heat Goes On)",
        "Crosseyed and Painless",
        "The Great Curve",
        "Once in a Lifetime",
        "Houses in Motion",
        "Seen and Not Seen",
        "Listening Wind",
        "The Overload",
        # Set 3
        "Brother",
        "Also Sprach Zarathustra",
        "Maze",
        "Simple",
        "Swept Away",
        "Steep",
        "Jesus Just Left Chicago",
        "Suzy Greenberg",
        "Frankenstein",
    ],
    "Live Phish 16": [
        # Set 1
        "Axilla",
        "Punch You in the Eye",
        "Roggae",
        "Birds of a Feather",
        "Sneakin' Sally Thru the Alley",
        "Chalk Dust Torture",
        "Lawn Boy",
        "Mike's Song",
        "Frankie Says",
        "Weekapaug Groove",
        # Set 2: Velvet Underground's Loaded (Halloween '98)
        "Who Loves the Sun?",
        "Sweet Jane",
        "Rock and Roll",
        "Cool It Down",
        "New Age",
        "Head Held High",
        "Lonesome Cowboy Bill",
        "I Found a Reason",
        "Train Round the Bend",
        "Oh! Sweet Nuthin'",
        # Set 3
        "Wolfman's Brother",
        "Piper",
        "Ghost",
        "Sleeping Monkey",
        "Tweezer Reprise",
        "Run Like an Antelope",
        "Stash",
        "Manteca",
        "Tweezer",
        "NICU",
        "Prince Caspian",
        "Golgi Apparatus",
        "Driver",
        "Free Bird",
    ],
    "Live Phish 17": [
        "Wolfman's Brother",
        "Water in the Sky",
        "The Moma Dance",
        "Guyute",
        "Horn",
        "Chalk Dust Torture",
        "Brian and Robert",
        "Beauty of My Dreams",
        "Cars Trucks Buses",
        "Roggae",
        "Birds of a Feather",
        "Loving Cup",
        "Limb By Limb",
        "Simple",
        "Tweezer",
        "California Love",
        "Free",
        "Meat",
        "Harry Hood",
        "Wilson",
        "Tweezer Reprise",
        "Bathtub Gin",
    ],
    "Live Phish 18": [
        "Llama",
        "Horn",
        "Divided Sky",
        "Mound",
        "Fast Enough for You",
        "Scent of a Mule",
        "Split Open and Melt",
        "If I Could",
        "Suzy Greenberg",
        "Loving Cup",
        "Sparkle",
        "Tweezer",
        "Sparks",
        "Makisupa Policeman",
        "Walk Away",
        "Cannonball",
        "Purple Rain",
        "Tweezer Reprise",
        "Amazing Grace",
        "Sample in a Jar",
        "Funky Bitch",
        "Yerushalayim Shel Zahav",
    ],
    "Live Phish 19": [
        "Dinner and a Movie",
        "Bouncing Around the Room",
        "Buried Alive",
        "Flat Fee",
        "Reba",
        "The Landlady",
        "Bathtub Gin",
        "Donna Lee",
        "AC/DC Bag",
        "Rocky Top",
        "Cavern",
        "David Bowie",
        "Golgi Apparatus",
        "The Squirming Coil",
        "Moose the Mooche",
        "Tweezer",
        "My Sweet One",
        "Gumbo",
        "Mike's Song",
        "I Am Hydrogen",
        "Weekapaug Groove",
        "Touch Me",
        "The Oh Kee Pa Ceremony",
        "Suzy Greenberg",
        "Sweet Adeline",
        "Frankenstein",
        "Fee",
        "Tweezer Reprise",
    ],
    "Live Phish 20": [
        "Runaway Jim",
        "Foam",
        "If I Could",
        "Split Open and Melt",
        "The Horse",
        "Silent in the Morning",
        "Uncle Pen",
        "I Didn't Know",
        "Possum",
        "Guyute",
        "David Bowie",
        "Halley's Comet",
        "The Lizards",
        "Cracklin' Rosie",
        "Good Times Bad Times",
        "My Long Journey Home",
        "Sleeping Monkey",
    ],
}
